import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Portfolio | DevLaunch AI',
  description: 'Developer Portfolio generated by DevLaunch AI',
};

export default function PortfolioPublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-50 font-sans selection:bg-indigo-500/30">
      {/* Global animated background glow */}
      <div className="fixed inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-indigo-500/20 rounded-full blur-[128px] opacity-50 mix-blend-screen animate-pulse duration-10000" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-[128px] opacity-50 mix-blend-screen" />
      </div>
      
      <main className="relative z-10 w-full overflow-x-hidden">
        {children}
      </main>
    </div>
  );
}
